### ISSUE TITLE
Please add support for the robots.txt file

### ISSUE THREAD

**Issue by ygguser** [YGGverse/YGGo#2]
Please add reading the [robots.txt](https://developers.google.com/search/docs/crawling-indexing/robots/intro) file and crawling based on its content in the crawler functions.

**Comment by d47081** [comment]
Nice think! forgot about this important moment

**Comment by d47081** [comment]
Hello, after #3 implementation, added the basic robots.txt support.

Maybe I wrote 'new bicycle' but as is.

For right now, crawler supports the `User-agent: *` section, `Allow`/`Disallow` constructions only.

Plus, have added the `CRAWL_ROBOTS_DEFAULT_RULES` directive to [config file](https://github.com/YGGverse/YGGo/blob/main/config/app.php.txt), where search provider can set own default rules, when the website does not provide this file.

For contributors, the library class presented here:
https://github.com/YGGverse/YGGo/blob/main/library/robots.php

Please reopen if I something missed.
